In [1]:
import numpy as np

In [2]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.shape

(5,)

In [18]:
## reshape
my_list2=[2,3,4,5,6]
arr=np.array([my_list,my_list2])

In [9]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [10]:
arr.shape

(2, 5)

In [11]:
arr.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]])

In [12]:
arr.shape

(2, 5)

In [13]:
arr=arr.reshape(5,2)

In [14]:
arr

array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]])

Indexing 

In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [16]:
arr[5]

6

In [19]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [23]:
arr[0:,0]

array([1, 2])

In [30]:
arr=np.arange(0,10)

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr=np.arange(0,10,2)

In [27]:
arr

array([0, 2, 4, 6, 8])

In [29]:
np.linspace(1,50,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr1=arr

In [36]:
arr1=arr.copy()

In [40]:
print(arr)
arr1[3:]=1000
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[   0    1    2 1000 1000 1000 1000 1000 1000 1000]


In [35]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr1

array([   0,    1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [45]:
val=2
arr%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [47]:
arr[arr<5]

array([0, 1, 2, 3, 4])

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [49]:
np.random.rand(2,2)

array([[0.5461831 , 0.09536473],
       [0.95613936, 0.28606533]])

In [51]:
rand=np.random.randn(3,3)

In [52]:
rand

array([[ 0.93889401, -0.58399218, -1.36620307],
       [-0.32281875,  0.95484834, -1.64546993],
       [ 0.81332417, -0.48695094, -1.36191814]])

In [53]:
ab=np.random.randint(0,100,8)

In [54]:
ab

array([16, 47, 90, 21, 52, 90,  8, 32])

In [55]:
ab.reshape(2,4)

array([[16, 47, 90, 21],
       [52, 90,  8, 32]])

In [58]:
np.random.random_sample((1,5))

array([[0.88841228, 0.17305017, 0.46434223, 0.49390394, 0.09782854]])